export const languages = [
	{ code: 'ru', name: 'Русский' },
	{ code: 'en', name: 'English' },
	{ code: 'es', name: 'Español' },
	{ code: 'de', name: 'Deutsch' },
	{ code: 'fr', name: 'Français' },
	{ code: 'it', name: 'Italiano' },
	{ code: 'pt', name: 'Português' },
	{ code: 'zh', name: '中文' },
	{ code: 'ja', name: '日本語' },
	{ code: 'ko', name: '한국어' },
	{ code: 'ar', name: 'العربية' },
	{ code: 'hi', name: 'हिन्दी' },
	{ code: 'bn', name: 'বাংলা' },
	{ code: 'pa', name: 'ਪੰਜਾਬੀ' },
	{ code: 'mr', name: 'मराठी' },
	{ code: 'gu', name: 'ગુજરાતી' },
	{ code: 'ta', name: 'தமிழ்' },
	{ code: 'te', name: 'తెలుగు' },
	{ code: 'kn', name: 'ಕನ್ನಡ' },
	{ code: 'ml', name: 'മലയാളം' },
	{ code: 'si', name: 'සිංහල' },
	{ code: 'th', name: 'ไทย' },
	{ code: 'vi', name: 'Tiếng Việt' },
	{ code: 'id', name: 'Bahasa Indonesia' },
	{ code: 'ms', name: 'Bahasa Melayu' },
	{ code: 'tl', name: 'Tagalog' },
	{ code: 'tr', name: 'Türkçe' },
	{ code: 'he', name: 'עברית' },
	{ code: 'fa', name: 'فارسی' },
	{ code: 'ur', name: 'اردو' },
	{ code: 'pl', name: 'Polski' },
	{ code: 'uk', name: 'Українська' },
	{ code: 'cs', name: 'Čeština' },
	{ code: 'sk', name: 'Slovenčina' },
	{ code: 'bg', name: 'Български' },
	{ code: 'hr', name: 'Hrvatski' },
	{ code: 'sr', name: 'Српски' },
	{ code: 'sl', name: 'Slovenščina' },
	{ code: 'ro', name: 'Română' },
	{ code: 'hu', name: 'Magyar' },
	{ code: 'el', name: 'Ελληνικά' },
	{ code: 'et', name: 'Eesti' },
	{ code: 'lv', name: 'Latviešu' },
	{ code: 'lt', name: 'Lietuvių' },
	{ code: 'fi', name: 'Suomi' },
	{ code: 'sv', name: 'Svenska' },
	{ code: 'no', name: 'Norsk' },
	{ code: 'da', name: 'Dansk' },
	{ code: 'is', name: 'Íslenska' },
	{ code: 'nl', name: 'Nederlands' },
	{ code: 'af', name: 'Afrikaans' },
	{ code: 'sq', name: 'Shqip' },
	{ code: 'hy', name: 'Հայերեն' },
	{ code: 'az', name: 'Azərbaycan' },
	{ code: 'ka', name: 'ქართული' },
	{ code: 'eu', name: 'Euskara' },
	{ code: 'ca', name: 'Català' },
	{ code: 'gl', name: 'Galego' },
	{ code: 'cy', name: 'Cymraeg' },
	{ code: 'ga', name: 'Gaeilge' },
	{ code: 'gd', name: 'Gàidhlig' },
	{ code: 'mt', name: 'Malti' },
	{ code: 'eo', name: 'Esperanto' },
	{ code: 'la', name: 'Latina' },
	{ code: 'sw', name: 'Kiswahili' },
	{ code: 'yo', name: 'Yorùbá' },
	{ code: 'ig', name: 'Igbo' },
	{ code: 'ha', name: 'Hausa' },
	{ code: 'zu', name: 'isiZulu' },
	{ code: 'xh', name: 'isiXhosa' },
	{ code: 'am', name: 'አማርኛ' },
	{ code: 'ti', name: 'ትግርኛ' },
	{ code: 'so', name: 'Soomaali' },
	{ code: 'mg', name: 'Malagasy' },
	{ code: 'ny', name: 'Chichewa' },
	{ code: 'sn', name: 'chiShona' },
	{ code: 'st', name: 'Sesotho' },
	{ code: 'tn', name: 'Setswana' },
	{ code: 'ss', name: 'siSwati' },
	{ code: 've', name: 'Tshivenda' },
	{ code: 'ts', name: 'Xitsonga' },
	{ code: 'nr', name: 'isiNdebele' },
	{ code: 'nso', name: 'Sepedi' },
	{ code: 'lg', name: 'Luganda' },
	{ code: 'ln', name: 'Lingála' },
	{ code: 'kg', name: 'Kikongo' },
	{ code: 'sg', name: 'Sängö' },
	{ code: 'rn', name: 'Kirundi' },
	{ code: 'rw', name: 'Kinyarwanda' },
	{ code: 'wo', name: 'Wolof' },
	{ code: 'ff', name: 'Fulfulde' },
	{ code: 'ee', name: 'Eʋegbe' },
	{ code: 'tw', name: 'Twi' },
	{ code: 'ak', name: 'Akan' },
	{ code: 'bm', name: 'Bamanankan' },
	{ code: 'dyu', name: 'Julakan' },
	{ code: 'mos', name: 'Mooré' },
	{ code: 'guw', name: 'gbe' },
	{ code: 'ht', name: 'Kreyòl Ayisyen' },
	{ code: 'jam', name: 'Jamaican Creole' },
	{ code: 'srn', name: 'Sranan Tongo' },
	{ code: 'fj', name: 'Na Vosa Vakaviti' },
	{ code: 'to', name: 'Lea Faka-Tonga' },
	{ code: 'sm', name: 'Gagana Samoa' },
	{ code: 'mi', name: 'Te Reo Māori' },
	{ code: 'haw', name: 'ʻŌlelo Hawaiʻi' },
	{ code: 'ty', name: 'Reo Tahiti' },
	{ code: 'mh', name: 'Kajin M̧ajeļ' },
	{ code: 'bi', name: 'Bislama' },
	{ code: 'ho', name: 'Hiri Motu' },
	{ code: 'tpi', name: 'Tok Pisin' },
	{ code: 'gil', name: 'Taetae ni Kiribati' },
	{ code: 'na', name: 'Dorerin Naoero' },
	{ code: 'niu', name: 'Ko e Vagahau Niuē' },
	{ code: 'tkl', name: 'Gagana Tokelau' },
	{ code: 'tvl', name: 'Te Ggana Tuuvalu' },
	{ code: 'pon', name: 'Pohnpeian' },
	{ code: 'chk', name: 'Chuukese' },
	{ code: 'yap', name: 'Yapese' },
	{ code: 'war', name: 'Winaray' },
	{ code: 'ceb', name: 'Cebuano' },
	{ code: 'ilo', name: 'Ilokano' },
	{ code: 'hil', name: 'Hiligaynon' },
	{ code: 'pag', name: 'Pangasinan' },
	{ code: 'bcl', name: 'Bikol' },
	{ code: 'pam', name: 'Kapampangan' },
	{ code: 'mdh', name: 'Maguindanao' },
	{ code: 'tsg', name: 'Sūg' },
	{ code: 'mrw', name: 'Maranao' },
	{ code: 'bto', name: 'Iriga Bicolano' },
	{ code: 'dtp', name: 'Dusun Bundu-Liwan' },
	{ code: 'kwn', name: 'Kwangali' },
	{ code: 'kqn', name: 'Kaonde' },
	{ code: 'lua', name: 'Tshiluba' },
	{ code: 'lue', name: 'Luvale' },
	{ code: 'lun', name: 'Lunda' },
	{ code: 'loz', name: 'Lozi' },
	{ code: 'tum', name: 'chiTumbuka' },
	{ code: 'nyk', name: 'Nyaneka' },
	{ code: 'umb', name: 'Umbundu' },
	{ code: 'kwy', name: 'Kikongo ya Leta' },
	{ code: 'swc', name: 'Kiswahili wa Kongo' },
	{ code: 'run', name: 'Kirundi' },
	{ code: 'mfe', name: 'Morisyen' },
	{ code: 'pap', name: 'Papiamentu' },
	{ code: 'pis', name: 'Pijin' },
	{ code: 'wls', name: 'Fakaʻuvea' },
	{ code: 'yua', name: 'Maya' },
	{ code: 'qu', name: 'Runa Simi' },
	{ code: 'ay', name: 'Aymar Aru' },
	{ code: 'gn', name: 'Avañeʼẽ' },
];
